### PR TITLE
Client-side code refactoring , (components , containers , utils , services ) 

### PR DESCRIPTION
**Pull request by Rebaiahmed**

### CODE REVIEW

**Comment by Rebaiahmed** [comment]
We will move to redux implementation with graphql client ? for server-side do you will migrate to graphql ?

**Comment by gayanvoice** [comment]
@Rebaiahmed You have refactored the entire app. Thank you. Before merging with the main branch can you add the corrections on LGTM code analysis. There are several unused variables and functions.

**Comment by Rebaiahmed** [comment]
I mean, the project name is node-graphql , but I didn't see any graphql implementation? and why the data is stored in MongoDB? why we didn't interact directly with Github API?

**Comment by gayanvoice** [comment]
Simply we can not use GitHub GraphQL directly at realtime. It takes 4 minutes to fetch 1,000 nodes. And also we can not fetch more than 10 nodes per request  otherwise it returns server error. So basically we can not call more than 5,000 requests.

https://developer.github.com/v4/guides/resource-limitations/

So that's why the app uses mongodb to store users

**Comment by Rebaiahmed** [comment]
Do you want to add more modules to the app? add more countries, server-side code optimization? migrate from the rest-API to graphql ? add InputSearch to filter country?

**Comment by gayanvoice** [comment]
@Rebaiahmed Every contribution is welcome. You can contribute to this app by improving, changing the design, layouts, speed, and etc. And also please create PRs for each major changes with appropriate descriptions.

**Comment by Rebaiahmed** [comment]
Thanks, this is my first contribution to open source project in GitHub,  excuse me if there are some issues in description or branching names or commits, I'm really excited to be one these contributors,
thanks 👍 🔍

**Comment by gayanvoice** [comment]
Welome @Rebaiahmed the previous one had so many changes in a single PR. Some of those implementations can review easily, but the PR can not merge until a full review. It will be easy, if there are few changes in each PR. For an example, you can create a PR for changes in server.js and create another for client app. Thank you.

**Comment by Rebaiahmed** [comment]
Ok man, so my PR will be accepted or not? 🗡 🤕 ?

**Comment by gayanvoice** [comment]
I have been busy these days buddy. I will merge it by within few days.

**Pull request closed without merging**
